version: '3.5'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    healthcheck:
        test: ['CMD-SHELL', 'pg_isready -U postgres']
        interval: 10s
        timeout: 5s
        retries: 60
  db-migration:
    build: 
      context: ./db
      dockerfile: Dockerfile    
    depends_on:
      - database
    # volumes:
    #   - ${PWD}/db/export:/tmp
    environment:
      - "DEBUG=1"                     # enable script debugging
      #- "LOCAL_DEVELOPMENT=1"         # will try to CREATE DATABASE ${PGDATABASE}
      - "PGDATABASE=postgres"     # database name
      - "PGHOST=database"             # same as avove - docker-compose service name
      - "PGPORT=5432"                 # same as above
      - "PGUSER=postgres"             # same as above
      - "PGPASSWORD=postgres"                # same as above
      - "PGSSLMODE=disable"           # ignore SSLMODE for local development (overwritten - see ./db/Dockerfile)